ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE ROLE RL_TAICHINH;

GRANT SELECT ON god.NHANVIEN TO RL_TAICHINH;
GRANT SELECT ON god.phancong TO RL_TAICHINH;
GRANT UPDATE (LUONG, PHUCAP) ON god.NHANVIEN TO RL_TAICHINH;

SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE = 'RL_TAICHINH';

UPDATE GOD.NHANVIEN SET LUONG = 10000 WHERE MANV='TC09';

CREATE OR REPLACE PROCEDURE usp_GrantUserTAICHINH
AS
    CURSOR CUR IS (SELECT MANV
                    FROM god.nhanvien
                    WHERE vaitro=N'Tài chính');
    strSQL VARCHAR(2000);
    Usr varchar2(30);
BEGIN
    OPEN CUR;
    strSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE';
    EXECUTE IMMEDIATE (strSQL);
    LOOP
        FETCH CUR INTO Usr;
        EXIT WHEN CUR%NOTFOUND;


        strSQL:= 'GRANT RL_TAICHINH TO '||Usr;
        EXECUTE IMMEDIATE (strSQL);
    END LOOP;
    strSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT"=FALSE';
    EXECUTE IMMEDIATE (strSQL);
END;
exec usp_GrantUserTAICHINH;
